package visao;

import buscacep.WebServiceCep;
import controle.ConectaBanco;
import controle.ControleCliente;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import modelo.ModeloCliente;
import modelo.ModeloProduto;
import modelo.ModeloTabela;
import modelo.NimbusClasse;

/**
 *
 * @author Haurio & Benson
 */
public class FrmCadastrarClientes extends javax.swing.JFrame {

    ConectaBanco conectaClientes = new ConectaBanco();
    ConectaBanco conectaCidade = new ConectaBanco();
    ConectaBanco conectapesquisa = new ConectaBanco();
    ModeloCliente mod = new ModeloCliente();
    ControleCliente control = new ControleCliente();
    DecimalFormat df = new DecimalFormat("0.00");
    int idCliente;
    int flag = 0;
    String estado;
    Float LimiteCompra;

    /**
     * Creates new form FrmClientes
     */
    public FrmCadastrarClientes() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        setIcon();
        novoProduto();
        EditaProduto();
        ExcluirProduto();
        salvaProduto();
        CancelarProduto();
        Sair();
        
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        iniciatabela();
        LimparTelaClientes();
        //preencherComboBox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCidade = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldRG = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CPF_CNPJ = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldInscricaoEs = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jTextFieldComplemento = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldIBGE = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBoxCidade = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxUF = new javax.swing.JComboBox<>();
        jTextFieldCEP = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldInscricaoMun = new javax.swing.JTextField();
        jTextFieldLimiteCompra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxTipoPess = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldCPF = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldApelido = new javax.swing.JTextField();
        jComboBoxDdd = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Clientes");
        setBackground(new java.awt.Color(0, 181, 181));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 181, 181));

        jButtonNovo.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNovo.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonNovo.setForeground(new java.awt.Color(0, 153, 153));
        jButtonNovo.setText("Novo (F6)");
        jButtonNovo.setToolTipText("Novo");
        jButtonNovo.setBorderPainted(false);
        jButtonNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonSalvar.setForeground(new java.awt.Color(0, 153, 153));
        jButtonSalvar.setText("Salvar (F12)");
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.setBorderPainted(false);
        jButtonSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEditar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonEditar.setForeground(new java.awt.Color(0, 153, 153));
        jButtonEditar.setText("Editar (F8)");
        jButtonEditar.setToolTipText("Editar");
        jButtonEditar.setBorderPainted(false);
        jButtonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setBackground(new java.awt.Color(255, 255, 255));
        jButtonExcluir.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonExcluir.setForeground(new java.awt.Color(0, 153, 153));
        jButtonExcluir.setText("Excluir (Del)");
        jButtonExcluir.setToolTipText("Excluir");
        jButtonExcluir.setBorderPainted(false);
        jButtonExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonSair.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSair.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonSair.setForeground(new java.awt.Color(0, 153, 153));
        jButtonSair.setText("Sair (ESC)");
        jButtonSair.setToolTipText("Sair");
        jButtonSair.setBorderPainted(false);
        jButtonSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        tabela.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabela.setForeground(new java.awt.Color(51, 51, 51));
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        tabela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jTextFieldPesquisa.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextFieldPesquisa.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldPesquisa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaActionPerformed(evt);
            }
        });
        jTextFieldPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Código:");

        jTextFieldCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldCodigo.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldCodigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldCodigo.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome do Cliente:");

        jTextFieldNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldNome.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldNome.setEnabled(false);
        jTextFieldNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNomeFocusLost(evt);
            }
        });
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jTextFieldRG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldRG.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldRG.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldRG.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RG:");

        CPF_CNPJ.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        CPF_CNPJ.setForeground(new java.awt.Color(255, 255, 255));
        CPF_CNPJ.setText("CPF/CNPJ:");

        jTextFieldEndereco.setEditable(false);
        jTextFieldEndereco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldEndereco.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldEndereco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldEndereco.setEnabled(false);
        jTextFieldEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnderecoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Endereço:");

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Bairro:");

        jTextFieldBairro.setEditable(false);
        jTextFieldBairro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldBairro.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldBairro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldBairro.setEnabled(false);

        jComboBoxSexo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxSexo.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        jComboBoxSexo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBoxSexo.setEnabled(false);
        jComboBoxSexo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxSexoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxSexoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBoxSexoMouseExited(evt);
            }
        });
        jComboBoxSexo.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jComboBoxSexoInputMethodTextChanged(evt);
            }
        });
        jComboBoxSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSexoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sexo:");

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Insc. Estadual:");

        jTextFieldInscricaoEs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldInscricaoEs.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldInscricaoEs.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldInscricaoEs.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nº:");

        jTextFieldNumero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldNumero.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldNumero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldNumero.setEnabled(false);

        jTextFieldComplemento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldComplemento.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldComplemento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldComplemento.setEnabled(false);
        jTextFieldComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldComplementoActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Complemento:");

        jTextFieldIBGE.setEditable(false);
        jTextFieldIBGE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldIBGE.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldIBGE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldIBGE.setEnabled(false);

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("IBGE:");

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("CEP:");

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("UF:");

        jComboBoxCidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxCidade.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxCidade.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBoxCidade.setEnabled(false);
        jComboBoxCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxCidadeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxCidadeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBoxCidadeMouseExited(evt);
            }
        });
        jComboBoxCidade.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jComboBoxCidadeInputMethodTextChanged(evt);
            }
        });
        jComboBoxCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCidadeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cidade:");

        jComboBoxUF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxUF.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxUF.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBoxUF.setEnabled(false);
        jComboBoxUF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxUFMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxUFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBoxUFMouseExited(evt);
            }
        });
        jComboBoxUF.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jComboBoxUFInputMethodTextChanged(evt);
            }
        });
        jComboBoxUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUFActionPerformed(evt);
            }
        });

        jTextFieldCEP.setForeground(new java.awt.Color(102, 102, 102));
        try {
            jTextFieldCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldCEP.setEnabled(false);
        jTextFieldCEP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCEPFocusLost(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Insc. Municipal:");

        jTextFieldInscricaoMun.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldInscricaoMun.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldInscricaoMun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldInscricaoMun.setEnabled(false);

        jTextFieldLimiteCompra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldLimiteCompra.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldLimiteCompra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldLimiteCompra.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Limite de Compra:");

        jComboBoxTipoPess.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jComboBoxTipoPess.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxTipoPess.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Física", "Jurídica" }));
        jComboBoxTipoPess.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBoxTipoPess.setEnabled(false);
        jComboBoxTipoPess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxTipoPessMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxTipoPessMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBoxTipoPessMouseExited(evt);
            }
        });
        jComboBoxTipoPess.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jComboBoxTipoPessInputMethodTextChanged(evt);
            }
        });
        jComboBoxTipoPess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoPessActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Tip. Pessoa:");

        jTextFieldCPF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldCPF.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldCPF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldCPF.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxTipoPess, 0, 116, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CPF_CNPJ)
                            .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldRG)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIBGE, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(172, 172, 172))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldInscricaoEs))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldInscricaoMun, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldLimiteCompra)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldEndereco)
                                .addGap(21, 21, 21)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel20)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldCodigo)
                                    .addComponent(jComboBoxTipoPess, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CPF_CNPJ)
                        .addGap(4, 4, 4)
                        .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(6, 6, 6)
                        .addComponent(jTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel15))
                        .addGap(7, 7, 7)
                        .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextFieldIBGE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel19)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jComboBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel17)
                                                .addComponent(jLabel12))
                                            .addGap(43, 43, 43))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(42, 42, 42))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextFieldInscricaoEs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldLimiteCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(44, 44, 44)))
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jTextFieldInscricaoMun, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Telefone:");

        jTextFieldTelefone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldTelefone.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldTelefone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldTelefone.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Email:");

        jTextFieldEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldEmail.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Apelido:");

        jTextFieldApelido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldApelido.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldApelido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldApelido.setEnabled(false);
        jTextFieldApelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApelidoActionPerformed(evt);
            }
        });
        jTextFieldApelido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldApelidoKeyPressed(evt);
            }
        });

        jComboBoxDdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxDdd.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxDdd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11", "12", "13", "14", "15", "16", "17", "18", "19", "21", "22", "24", "27", "28", "31", "32", "33", "34", "35", "37", "38", "41", "42", "43", "44", "45", "46", "47", "48", "49", "51", "53", "54", "55", "61", "62", "63", "64", "65", "66", "67", "68", "69", "71", "73", "74", "75", "77", "79", "81", "82", "83", "84", "85", "86", "87", "88", "89", "91", "92", "93", "94", "95", "96", "97", "98", "99", " " }));
        jComboBoxDdd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBoxDdd.setEnabled(false);
        jComboBoxDdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxDddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxDddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBoxDddMouseExited(evt);
            }
        });
        jComboBoxDdd.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jComboBoxDddInputMethodTextChanged(evt);
            }
        });
        jComboBoxDdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDddActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("DDD:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxDdd, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldEmail))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jButtonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(0, 153, 153));
        jButtonCancelar.setText("Cancelar (F7)");
        jButtonCancelar.setToolTipText("Excluir");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSair))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCidade)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCidade)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1320, 738));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 2;

        habilitarCamposclientes();
        jTextFieldPesquisa.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        jButtonExcluir.setEnabled(false);

    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        if (jTextFieldNome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo NOME DO CLIENTE esta sem preenchimento!");
            jTextFieldNome.requestFocus();

        } else if (jTextFieldRG.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo RG esta sem preenchimento!");
            jTextFieldRG.requestFocus();

        } else if (jTextFieldRG.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo CPF esta sem preenchimento!");
            jTextFieldRG.requestFocus();

        } else if (jTextFieldLimiteCompra.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informar o LIMITE DE COMPRA para o cliente que realiza o cadastro!");
            jTextFieldLimiteCompra.requestFocus();

        } else if (jTextFieldEndereco.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo ENDEREÇO esta sem preenchimento!");
            jTextFieldEndereco.requestFocus();

        } else if (jTextFieldBairro.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo BAIRRO esta sem preenchimento!");
            jTextFieldBairro.requestFocus();

        } else if (jTextFieldTelefone.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo TELEFONE esta sem preenchimento!");
            jTextFieldTelefone.requestFocus();

        } else if (jTextFieldEmail.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo EMAIL esta sem preenchimento!");
            jTextFieldEmail.requestFocus();

        } else if (jTextFieldApelido.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo APELIDO esta sem preenchimento!");
            jTextFieldApelido.requestFocus();

        } else if (flag == 0) {

            Cadastrar();

            LimparTelaClientes();
            bloquearCamposClientes();
            jTextFieldPesquisa.setEnabled(true);
            jButtonCancelar.setEnabled(false);
            jButtonExcluir.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            jComboBoxUF.setSelectedIndex(-1);
            jComboBoxCidade.setSelectedIndex(-1);
            

        } else {
            Editar();
        }
        LimparTelaClientes();
        bloquearCamposClientes();
        jTextFieldPesquisa.setEnabled(true);
        jButtonCancelar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jComboBoxUF.setSelectedIndex(-1);
        jComboBoxCidade.setSelectedIndex(-1);
       


    }//GEN-LAST:event_jButtonSalvarActionPerformed
    public void Cadastrar() {
        jButtonNovo.setEnabled(true);

        mod.setNome(jTextFieldNome.getText());
        mod.setTipo_pessoa((String) jComboBoxTipoPess.getSelectedItem());
        mod.setCpf(jTextFieldCPF.getText());
        mod.setRg(jTextFieldRG.getText());
        mod.setSexo((String) jComboBoxSexo.getSelectedItem());
        mod.setCep(jTextFieldCEP.getText().replace("-", ""));
        mod.setEndereco(jTextFieldEndereco.getText());
        mod.setNumero(jTextFieldNumero.getText());
        mod.setComplemento((String) jTextFieldComplemento.getText());
        mod.setIbge(jTextFieldIBGE.getText());
        mod.setUf((String) jComboBoxUF.getSelectedItem());
        mod.setCidade((String) jComboBoxCidade.getSelectedItem());
        mod.setBairro((String) jTextFieldBairro.getText());
        mod.setInscricao_estadual((String) jTextFieldInscricaoEs.getText());
        mod.setInscricao_municipal(jTextFieldInscricaoMun.getText());
        mod.setLimite(Float.parseFloat(jTextFieldLimiteCompra.getText().replace(",", ".")));
        mod.setTelefone(jTextFieldTelefone.getText());
        mod.setEmail((String) jTextFieldEmail.getText());
        mod.setApelido((String) jTextFieldApelido.getText());
        mod.setDdd((String)jComboBoxDdd.getSelectedItem());
        
        control.InserirCliente(mod);
        LimparTelaClientes();
        iniciatabela();
        jTextFieldNome.requestFocus();
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jComboBoxUF.setSelectedIndex(-1);
        jComboBoxCidade.setSelectedIndex(-1);
    }

    public void Editar() {
        mod.setId(Integer.parseInt(jTextFieldCodigo.getText()));
        mod.setTipo_pessoa((String) jComboBoxTipoPess.getSelectedItem());
        mod.setNome(jTextFieldNome.getText());
        mod.setCpf(jTextFieldCPF.getText());
        mod.setRg(jTextFieldRG.getText());
        mod.setSexo((String) jComboBoxSexo.getSelectedItem());
        mod.setCep(jTextFieldCEP.getText().replace("-", ""));
        mod.setEndereco(jTextFieldEndereco.getText());
        mod.setNumero(jTextFieldNumero.getText());
        mod.setComplemento((String) jTextFieldComplemento.getText());
        mod.setIbge(jTextFieldIBGE.getText());
        mod.setUf((String) jComboBoxUF.getSelectedItem());
        mod.setCidade((String) jComboBoxCidade.getSelectedItem());
        mod.setBairro((String) jTextFieldBairro.getText());
        mod.setInscricao_estadual((String) jTextFieldInscricaoEs.getText());
        mod.setInscricao_municipal(jTextFieldInscricaoMun.getText());
        mod.setLimite(Float.parseFloat(jTextFieldLimiteCompra.getText().replace(",", ".")));
        mod.setTelefone(jTextFieldTelefone.getText());
        mod.setEmail((String) jTextFieldEmail.getText());
        mod.setApelido((String) jTextFieldApelido.getText());
        mod.setDdd((String)jComboBoxDdd.getSelectedItem());
        control.AlterarCliente(mod);
        LimparTelaClientes();

        iniciatabela();
        jTextFieldNome.requestFocus();
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);

    }
    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed

        habilitarCamposclientes();
        LimparTelaClientes();

        jTextFieldPesquisa.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonCancelar.setEnabled(true);

        LimparTelaClientes();
        // chamaIdCliente();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        jButtonSalvar.setEnabled(false);
        jButtonExcluir.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonCancelar.setEnabled(true);
       
        String nome_cliente = "" + tabela.getValueAt(tabela.getSelectedRow(), 0);
        conectaClientes.conexao();
        conectapesquisa.conexao();
        conectaClientes.executaSQL("SELECT * FROM clientes WHERE id_cliente ='" + nome_cliente + "'");
        
        try {
            conectaClientes.rs.first();
            jTextFieldCodigo.setText(String.valueOf(conectaClientes.rs.getInt("id_cliente")));
            jTextFieldNome.setText(conectaClientes.rs.getString("nome_cliente"));
            jComboBoxTipoPess.setSelectedItem(conectaClientes.rs.getString("tipo_pessoa"));
            jTextFieldCPF.setText(String.valueOf(conectaClientes.rs.getString("cpf_cliente")));
            jTextFieldRG.setText(String.valueOf(conectaClientes.rs.getString("rg_cliente")));
            jComboBoxSexo.setSelectedItem(conectaClientes.rs.getString("sexo"));
            jTextFieldCEP.setText(conectaClientes.rs.getString("cep"));
            jTextFieldEndereco.setText(String.valueOf(conectaClientes.rs.getString("endereco_cliente")));
            jTextFieldTelefone.setText(String.valueOf(conectaClientes.rs.getString("telefone")));
            jTextFieldBairro.setText(conectaClientes.rs.getString("bairro"));
            jTextFieldLimiteCompra.setText(String.valueOf(df.format(conectaClientes.rs.getFloat("limite_compra"))).replace(".", ","));
            jTextFieldEmail.setText(String.valueOf(conectaClientes.rs.getString("email")));
            jTextFieldApelido.setText(String.valueOf(conectaClientes.rs.getString("apelido")));
            jComboBoxSexo.setSelectedItem(conectaClientes.rs.getString("sexo"));
            jTextFieldInscricaoEs.setText(String.valueOf(conectaClientes.rs.getString("inscricao_estadual")));
            jTextFieldInscricaoMun.setText(conectaClientes.rs.getString("inscricao_municipal"));
            jTextFieldNumero.setText(String.valueOf(conectaClientes.rs.getString("numero")));
            jTextFieldComplemento.setText(String.valueOf(conectaClientes.rs.getString("complemento")));
            jTextFieldIBGE.setText(String.valueOf(conectaClientes.rs.getString("ibge")));
            jComboBoxUF.addItem(conectaClientes.rs.getString("uf"));
            jComboBoxCidade.addItem(conectaClientes.rs.getString("cidade"));
            jComboBoxDdd.setSelectedItem(conectaClientes.rs.getString("ddd"));
            
            
//            conectapesquisa.executaSQL("SELECT * FROM cidade WHERE id_cidade =" + conectaClientes.rs.getInt("id_cidade"));
//            conectapesquisa.rs.first();
//
//            conectapesquisa.executaSQL("SELECT * FROM cidade WHERE id_cidade =" + conectaClientes.rs.getInt("id_cidade"));
//            conectapesquisa.rs.first();
//
//            jComboBoxCidade.setSelectedItem(conectapesquisa.rs.getString("nome_cidade"));

            //JOptionPane.showMessageDialog(null, nome_cliente);
        } catch (SQLException ex) {
           // JOptionPane.showMessageDialog(null, "Erro ao Selecionar os Dados" + ex);
        } finally {

           // conectapesquisa.desconecta();
            conectaClientes.desconecta();
        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void jTextFieldPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            if (!jTextFieldPesquisa.getText().equals("")) {
//                jButtonSalvar.setEnabled(false);
//                jButtonNovo.setEnabled(true);
//                jButtonEditar.setEnabled(true);
//                jButtonExcluir.setEnabled(true);
//                
//                mod.setPesquisa(jTextFieldPesquisa.getText());
//                ModeloCliente model = control.pesquisaCliente(mod);

               iniciatabela();

            } else {

                JOptionPane.showMessageDialog(rootPane, "Preencher com Nome");

            }

        }
    }//GEN-LAST:event_jTextFieldPesquisaKeyPressed

    private void iniciatabela() {

  preencherTabela("select * from clientes WHERE nome_cliente LIKE '%" + jTextFieldPesquisa.getText() + "%' ORDER BY nome_cliente ASC");
        
    }

    public void chamaIdCliente() {

        conectaClientes.conexao();

        try {
            conectaClientes.executaSQL("SELECT id_cliente FROM clientes");
            conectaClientes.rs.last();
            idCliente = conectaClientes.rs.getInt("id_cliente");
            jTextFieldCodigo.setText(String.valueOf(idCliente + 1));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Nenhum Cliente Cadastrado");
        } finally {

            conectaClientes.desconecta();

        }
    }
    private void jComboBoxCidadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxCidadeMouseEntered

    }//GEN-LAST:event_jComboBoxCidadeMouseEntered

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
         String message = "Deseja Excluir Cliente ?";
        String title = "Excluir Cliente";

        int result = JOptionPane.showConfirmDialog(this, message, title, JOptionPane.YES_OPTION);

        if (result == JOptionPane.YES_OPTION) {

            mod.setId(Integer.parseInt(jTextFieldCodigo.getText()));
           control.ExcluirCliente(mod);

            
        LimparTelaClientes();
        iniciatabela();
        bloquearCamposClientes();
          

            jButtonSalvar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            jButtonCancelar.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jButtonExcluir.setEnabled(false);

        } else {

            JOptionPane.showMessageDialog(null, "Cliente não Excluido!");
        }
        
        
        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jComboBoxCidadeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxCidadeMouseExited

    }//GEN-LAST:event_jComboBoxCidadeMouseExited

    private void jComboBoxCidadeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jComboBoxCidadeInputMethodTextChanged
      
    }//GEN-LAST:event_jComboBoxCidadeInputMethodTextChanged

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnderecoActionPerformed

    private void jTextFieldApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApelidoActionPerformed

    private void jTextFieldApelidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApelidoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            Cadastrar();
        }
    }//GEN-LAST:event_jTextFieldApelidoKeyPressed

    private void jComboBoxCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxCidadeMouseClicked

    }//GEN-LAST:event_jComboBoxCidadeMouseClicked

    private void jTextFieldPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyReleased
     iniciatabela();
    }//GEN-LAST:event_jTextFieldPesquisaKeyReleased

    private void jComboBoxSexoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxSexoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSexoMouseClicked

    private void jComboBoxSexoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxSexoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSexoMouseEntered

    private void jComboBoxSexoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxSexoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSexoMouseExited

    private void jComboBoxSexoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jComboBoxSexoInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSexoInputMethodTextChanged

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        LimparTelaClientes();
        bloquearCamposClientes();

        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jComboBoxUF.setSelectedIndex(-1);
        jComboBoxCidade.setSelectedIndex(-1);


    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaActionPerformed

    private void jComboBoxSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSexoActionPerformed

    private void jTextFieldComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldComplementoActionPerformed

    private void jComboBoxUFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxUFMouseClicked

    }//GEN-LAST:event_jComboBoxUFMouseClicked

    private void jComboBoxUFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxUFMouseEntered

    }//GEN-LAST:event_jComboBoxUFMouseEntered

    private void jComboBoxUFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxUFMouseExited

    }//GEN-LAST:event_jComboBoxUFMouseExited

    private void jComboBoxUFInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jComboBoxUFInputMethodTextChanged
//       

    }//GEN-LAST:event_jComboBoxUFInputMethodTextChanged

    private void jComboBoxUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUFActionPerformed

    private void jComboBoxCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCidadeActionPerformed
        BuscaIBGE();
    }//GEN-LAST:event_jComboBoxCidadeActionPerformed

    private void jComboBoxTipoPessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTipoPessMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoPessMouseClicked

    private void jComboBoxTipoPessMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTipoPessMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoPessMouseEntered

    private void jComboBoxTipoPessMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTipoPessMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoPessMouseExited

    private void jComboBoxTipoPessInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jComboBoxTipoPessInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoPessInputMethodTextChanged

    private void jComboBoxTipoPessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoPessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoPessActionPerformed

    private void jTextFieldNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNomeFocusLost
        // Verificando qual é o tipo de pessoa. add 10/04/2018

        switch (jComboBoxTipoPess.getSelectedIndex()) {
            case 0:
                CPF_CNPJ.setText("CPF:");
                //JOptionPane.showMessageDialog(null, "PESSOA FISICA");
                break;
            case 1:
                CPF_CNPJ.setText("CNPJ:");
                jTextFieldRG.setEnabled(false);
                jComboBoxUF.setEnabled(false);
                jComboBoxCidade.setEnabled(false);
                jTextFieldIBGE.setEnabled(false);
                jTextFieldEndereco.setEnabled(false);
                jTextFieldBairro.setEnabled(false);
                jTextFieldRG.setText("00000");
                //JOptionPane.showMessageDialog(null, "PESSOA JURIDICA");
                break;
            default:
                JOptionPane.showMessageDialog(null, "Selecione o Tipo de Cliente");
        }
    }//GEN-LAST:event_jTextFieldNomeFocusLost

    private void jTextFieldCEPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCEPFocusLost
        buscaCep();
    }//GEN-LAST:event_jTextFieldCEPFocusLost

    private void tabelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaKeyReleased
        jButtonSalvar.setEnabled(false);
        jButtonExcluir.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        String nome_cliente = "" + tabela.getValueAt(tabela.getSelectedRow(), 0);
        conectaClientes.conexao();
        conectapesquisa.conexao();
        conectaClientes.executaSQL("SELECT * FROM clientes WHERE id_cliente ='" + nome_cliente + "'");
        
        try {
            conectaClientes.rs.first();
            jTextFieldCodigo.setText(String.valueOf(conectaClientes.rs.getInt("id_cliente")));
            jTextFieldNome.setText(conectaClientes.rs.getString("nome_cliente"));
            jComboBoxTipoPess.setSelectedItem(conectaClientes.rs.getString("tipo_pessoa"));
            jTextFieldCPF.setText(String.valueOf(conectaClientes.rs.getString("cpf_cliente")));
            jTextFieldRG.setText(String.valueOf(conectaClientes.rs.getString("rg_cliente")));
            jComboBoxSexo.setSelectedItem(conectaClientes.rs.getString("sexo"));
            jTextFieldCEP.setText(conectaClientes.rs.getString("cep"));
            jTextFieldEndereco.setText(String.valueOf(conectaClientes.rs.getString("endereco_cliente")));
            jTextFieldTelefone.setText(String.valueOf(conectaClientes.rs.getString("telefone")));
            jTextFieldBairro.setText(conectaClientes.rs.getString("bairro"));
            jTextFieldLimiteCompra.setText(String.valueOf(df.format(conectaClientes.rs.getFloat("limite_compra"))).replace(".", ","));
            jTextFieldEmail.setText(String.valueOf(conectaClientes.rs.getString("email")));
            jTextFieldApelido.setText(String.valueOf(conectaClientes.rs.getString("apelido")));
            jComboBoxSexo.setSelectedItem(conectaClientes.rs.getString("sexo"));
            jTextFieldInscricaoEs.setText(String.valueOf(conectaClientes.rs.getString("inscricao_estadual")));
            jTextFieldInscricaoMun.setText(conectaClientes.rs.getString("inscricao_municipal"));
            jTextFieldNumero.setText(String.valueOf(conectaClientes.rs.getString("numero")));
            jTextFieldComplemento.setText(String.valueOf(conectaClientes.rs.getString("complemento")));
            jTextFieldIBGE.setText(String.valueOf(conectaClientes.rs.getString("ibge")));
            jComboBoxUF.addItem(conectaClientes.rs.getString("uf"));
            jComboBoxCidade.addItem(conectaClientes.rs.getString("cidade"));
            jComboBoxDdd.setSelectedItem(conectaClientes.rs.getString("ddd"));
            
            
//            conectapesquisa.executaSQL("SELECT * FROM cidade WHERE id_cidade =" + conectaClientes.rs.getInt("id_cidade"));
//            conectapesquisa.rs.first();
//
//            conectapesquisa.executaSQL("SELECT * FROM cidade WHERE id_cidade =" + conectaClientes.rs.getInt("id_cidade"));
//            conectapesquisa.rs.first();
//
//            jComboBoxCidade.setSelectedItem(conectapesquisa.rs.getString("nome_cidade"));

            //JOptionPane.showMessageDialog(null, nome_cliente);
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(null, "Erro ao Selecionar os Dados" + ex);
        } finally {

           // conectapesquisa.desconecta();
            conectaClientes.desconecta();
        }
    }//GEN-LAST:event_tabelaKeyReleased

    private void jComboBoxDddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxDddMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDddMouseClicked

    private void jComboBoxDddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxDddMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDddMouseEntered

    private void jComboBoxDddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxDddMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDddMouseExited

    private void jComboBoxDddInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jComboBoxDddInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDddInputMethodTextChanged

    private void jComboBoxDddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDddActionPerformed

    public void LimparTelaClientes() {
        jTextFieldCodigo.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldNome.setText("");
        jTextFieldCPF.setText("");
        jTextFieldRG.setText("");
        jTextFieldBairro.setText("");
        jTextFieldLimiteCompra.setText("");
        jTextFieldTelefone.setText("");
        jTextFieldEmail.setText("");
        jTextFieldApelido.setText("");
        jTextFieldInscricaoEs.setText("");
        jTextFieldInscricaoMun.setText("");
        jTextFieldIBGE.setText("");
        jTextFieldNumero.setText("");
        jTextFieldCEP.setText("");
        jTextFieldComplemento.setText("");
        jTextFieldPesquisa.setText("");
        jComboBoxSexo.setSelectedIndex(-1);
        jComboBoxTipoPess.setSelectedIndex(-1);
        jComboBoxDdd.setSelectedIndex(-1);

    }

    public void preencherComboBox() {

        jComboBoxUF.removeAllItems();
        conectaClientes.conexao();
        
        conectaClientes.executaSQL("SELECT * FROM ddd ORDER BY prefixo");
        

        try {
            conectaClientes.rs.first();
            do {

                jComboBoxDdd.addItem(conectaClientes.rs.getString("prefixo"));
            } while (conectaClientes.rs.next());

            

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERRO AO CONECTAR" + ex);
        } finally {

            conectaClientes.desconecta();
        }

    }

    public void habilitarCamposclientes() {

        jTextFieldApelido.setEnabled(true);
        jTextFieldBairro.setEnabled(true);
        jTextFieldCPF.setEnabled(true);
        jTextFieldCodigo.setEnabled(false);
        jTextFieldEmail.setEnabled(true);
        jTextFieldEndereco.setEnabled(true);
        jTextFieldLimiteCompra.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jTextFieldRG.setEnabled(true);
        jTextFieldTelefone.setEnabled(true);
        jComboBoxSexo.setEnabled(true);
        jComboBoxCidade.setEnabled(true);
        jTextFieldInscricaoEs.setEnabled(true);
        jTextFieldInscricaoMun.setEnabled(true);
        jTextFieldIBGE.setEnabled(true);
        jTextFieldNumero.setEnabled(true);
        jTextFieldCEP.setEnabled(true);
        jTextFieldComplemento.setEnabled(true);
        jTextFieldPesquisa.setEnabled(true);
        jComboBoxUF.setEnabled(true);
        jTextFieldInscricaoEs.setEnabled(true);
        jComboBoxTipoPess.setEnabled(true);
        jComboBoxDdd.setEnabled(true);
    }

    public void bloquearCamposClientes() {
        jTextFieldApelido.setEnabled(false);
        jTextFieldBairro.setEnabled(false);
        jTextFieldCPF.setEnabled(false);
        jTextFieldRG.setEnabled(false);
        jTextFieldCodigo.setEnabled(false);
        jTextFieldEmail.setEnabled(false);
        jTextFieldEndereco.setEnabled(false);
        jTextFieldLimiteCompra.setEnabled(false);
        jTextFieldNome.setEnabled(false);
        jTextFieldRG.setEnabled(false);
        jTextFieldTelefone.setEnabled(false);
        jComboBoxSexo.setEnabled(false);
        jTextFieldInscricaoEs.setEnabled(false);
        jTextFieldInscricaoMun.setEnabled(false);
        jTextFieldPesquisa.setEnabled(true);
        jComboBoxCidade.setEnabled(false);
        jTextFieldIBGE.setEnabled(false);
        jTextFieldNumero.setEnabled(false);
        jTextFieldCEP.setEnabled(false);
        jTextFieldComplemento.setEnabled(false);
        jComboBoxUF.setEnabled(false);
        jTextFieldInscricaoEs.setEnabled(false);
        jComboBoxTipoPess.setEnabled(false);
        jComboBoxDdd.setEnabled(false);

    }

    public void BuscaIBGE() {
        conectaClientes.conexao();
        conectaClientes.executaSQL("SELECT *FROM cidades WHERE municipio LIKE '%" + jComboBoxCidade.getSelectedItem() + "%' ORDER BY municipio ASC");
        try {
            conectaClientes.rs.first();

            do {
                jTextFieldIBGE.setText(conectaClientes.rs.getString("codigo_ibge"));

            } while (conectaClientes.rs.next());

        } catch (SQLException ex) {
           // Logger.getLogger(FrmDadosEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void buscaCep() {
        //Faz a busca para o cep 58043-280
        WebServiceCep webServiceCep = WebServiceCep.searchCep(jTextFieldCEP.getText());
        //A ferramenta de busca ignora qualquer caracter que n?o seja n?mero.

        //caso a busca ocorra bem, imprime os resultados.
        jComboBoxCidade.removeAllItems();
        jComboBoxUF.removeAllItems();

        if (webServiceCep.wasSuccessful()) {
            jTextFieldEndereco.setText(webServiceCep.getLogradouroFull());
            jComboBoxCidade.addItem(webServiceCep.getCidade());
            jTextFieldBairro.setText(webServiceCep.getBairro());
            jComboBoxUF.addItem(webServiceCep.getUf());
            System.out.println("Cep: " + webServiceCep.getCep());
            System.out.println("Logradouro: " + webServiceCep.getLogradouroFull());
            System.out.println("Bairro: " + webServiceCep.getBairro());
            System.out.println("Cidade: "
                    + webServiceCep.getCidade() + "/" + webServiceCep.getUf());

            //caso haja problemas imprime as exce??es.
        } else {
            JOptionPane.showMessageDialog(null, "Erro numero: " + webServiceCep.getResulCode());

            JOptionPane.showMessageDialog(null, "Descrição do erro: " + webServiceCep.getResultText());
        }
    }

    public void preencherTabela(String SQL) {

        ArrayList dados = new ArrayList();

        String[] Colunas = new String[]{"ID", "Cliente","TIPO", "CPF/CNPJ","RG","Sexo","CEP","Endereço","Nº","Complemento","IBGE","UF","Cidade","Bairro","Insc.Estadual",
        "Insc.Municipal","Limite","DDD","Fone","Email","Apelido"};
        conectaClientes.conexao();
        conectaClientes.executaSQL(SQL);

        try {

            conectaClientes.rs.first();

            do {
                float LimiteCompra = conectaClientes.rs.getFloat("limite_compra");
                dados.add(new Object[]{conectaClientes.rs.getInt("id_cliente"), conectaClientes.rs.getString("nome_cliente"),conectaClientes.rs.getString("tipo_pessoa"),
                    conectaClientes.rs.getString("cpf_cliente"), conectaClientes.rs.getString("rg_cliente"), conectaClientes.rs.getString("sexo"), 
                    conectaClientes.rs.getString("cep"), conectaClientes.rs.getString("endereco_cliente"), conectaClientes.rs.getString("numero"), 
                    conectaClientes.rs.getString("complemento"),conectaClientes.rs.getString("ibge"), conectaClientes.rs.getString("uf"),
                    conectaClientes.rs.getString("cidade"), conectaClientes.rs.getString("bairro"), conectaClientes.rs.getString("inscricao_estadual"),
                    conectaClientes.rs.getString("inscricao_municipal"),conectaClientes.rs.getFloat("limite_compra"),conectaClientes.rs.getString("ddd"),conectaClientes.rs.getString("telefone"),
                    conectaClientes.rs.getString("email"),conectaClientes.rs.getString("apelido")}); 
            } while (conectaClientes.rs.next());
            } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "ERRO AO CONECTAR"+ e);
        } finally {

            conectaClientes.desconecta();
        }

        ModeloTabela modelo = new ModeloTabela(dados, Colunas);

        tabela.setModel(modelo);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(40); // ID
        tabela.getColumnModel().getColumn(0).setResizable(false);
        tabela.getColumnModel().getColumn(1).setPreferredWidth(300); // Nome Cliente
        tabela.getColumnModel().getColumn(1).setResizable(false);
        tabela.getColumnModel().getColumn(2).setPreferredWidth(80); // Tipo Pessoa
        tabela.getColumnModel().getColumn(2).setResizable(false);
        tabela.getColumnModel().getColumn(3).setPreferredWidth(150); // CPF
        tabela.getColumnModel().getColumn(3).setResizable(false);
        tabela.getColumnModel().getColumn(4).setPreferredWidth(80); // RG
        tabela.getColumnModel().getColumn(4).setResizable(false);
        tabela.getColumnModel().getColumn(5).setPreferredWidth(80); //Sexo
        tabela.getColumnModel().getColumn(5).setResizable(false);
        tabela.getColumnModel().getColumn(6).setPreferredWidth(80); //CEP
        tabela.getColumnModel().getColumn(6).setResizable(false);
        tabela.getColumnModel().getColumn(7).setPreferredWidth(300); // Endereço
        tabela.getColumnModel().getColumn(7).setResizable(false);
        tabela.getColumnModel().getColumn(8).setPreferredWidth(70); //Numero
        tabela.getColumnModel().getColumn(8).setResizable(false);
        tabela.getColumnModel().getColumn(9).setPreferredWidth(150); // Complemento
        tabela.getColumnModel().getColumn(9).setResizable(false);
        tabela.getColumnModel().getColumn(10).setPreferredWidth(80); //IBGE
        tabela.getColumnModel().getColumn(10).setResizable(false);
        tabela.getColumnModel().getColumn(11).setPreferredWidth(50); //UF
        tabela.getColumnModel().getColumn(11).setResizable(false);
        tabela.getColumnModel().getColumn(12).setPreferredWidth(60); //ID Cidade
        tabela.getColumnModel().getColumn(12).setResizable(false);
        tabela.getColumnModel().getColumn(13).setPreferredWidth(150); //Bairro
        tabela.getColumnModel().getColumn(13).setResizable(false);
        tabela.getColumnModel().getColumn(14).setPreferredWidth(80); //Inscrição Estadual
        tabela.getColumnModel().getColumn(14).setResizable(false);
        tabela.getColumnModel().getColumn(15).setPreferredWidth(80); //Inscrição Municipal
        tabela.getColumnModel().getColumn(15).setResizable(false);
        tabela.getColumnModel().getColumn(16).setPreferredWidth(80); //Limite de Compra
        tabela.getColumnModel().getColumn(16).setResizable(false);
        tabela.getColumnModel().getColumn(17).setPreferredWidth(80);// DDD
        tabela.getColumnModel().getColumn(17).setResizable(false);
        tabela.getColumnModel().getColumn(18).setPreferredWidth(80);// Telefone
        tabela.getColumnModel().getColumn(18).setResizable(false);
        tabela.getColumnModel().getColumn(19).setPreferredWidth(100); // Email
        tabela.getColumnModel().getColumn(19).setResizable(false);
        tabela.getColumnModel().getColumn(20).setPreferredWidth(150);// Apelido
        tabela.getColumnModel().getColumn(20).setResizable(false);
      
        

        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.setAutoResizeMode(tabela.AUTO_RESIZE_OFF);
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tabela.setRowHeight(28);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastrarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPF_CNPJ;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxCidade;
    private javax.swing.JComboBox<String> jComboBoxDdd;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JComboBox<String> jComboBoxTipoPess;
    private javax.swing.JComboBox<String> jComboBoxUF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldApelido;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JFormattedTextField jTextFieldCEP;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldIBGE;
    private javax.swing.JTextField jTextFieldInscricaoEs;
    private javax.swing.JTextField jTextFieldInscricaoMun;
    private javax.swing.JTextField jTextFieldLimiteCompra;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldRG;
    private javax.swing.JTextField jTextFieldTelefone;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
    private void novoProduto() {
        javax.swing.InputMap inputMap = this.getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F6, 0), "novo");
        this.getRootPane().setInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("novo", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            public void actionPerformed(ActionEvent arg0) {
                jButtonNovo.doClick();
            }
        });
    }

    private void salvaProduto() {
        javax.swing.InputMap inputMap = this.getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F12, 0), "salvar");
        this.getRootPane().setInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("salvar", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            public void actionPerformed(ActionEvent arg0) {
                jButtonSalvar.doClick();
            }
        });
    }

    private void EditaProduto() {
        javax.swing.InputMap inputMap = this.getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F8, 0), "edita");
        this.getRootPane().setInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("edita", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            public void actionPerformed(ActionEvent arg0) {
                jButtonEditar.doClick();
            }
        });
    }

    private void ExcluirProduto() {
        javax.swing.InputMap inputMap = this.getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_DELETE, 0), "exclui");
        this.getRootPane().setInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("exclui", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            public void actionPerformed(ActionEvent arg0) {
                jButtonExcluir.doClick();
            }
        });
    }

    private void Sair() {
        javax.swing.InputMap inputMap = this.getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "escape");
        this.getRootPane().setInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("escape", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            public void actionPerformed(ActionEvent arg0) {
                jButtonSair.doClick();
            }
        });
    }

    private void CancelarProduto() {
        javax.swing.InputMap inputMap = this.getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F7, 0), "cancela");
        this.getRootPane().setInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("cancela", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            public void actionPerformed(ActionEvent arg0) {
                jButtonCancelar.doClick();

            }
        });
    }

    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

}
