/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConectaBanco;
import controle.ControleVeiculos;
import static java.awt.SystemColor.control;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.AbstractAction;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import modelo.ModeloTabela;
import modelo.ModeloVeiculo;
import util.TarefasSegundoPlano;

/**
 *
 * @author Haurio-PC
 */
public class FrmCadastraVeiculo extends javax.swing.JFrame {

    ConectaBanco conecta = new ConectaBanco();
    ModeloVeiculo mod = new ModeloVeiculo();
    ControleVeiculos control = new ControleVeiculos();
    Date hoje = new Date();
    DateFormat data = new SimpleDateFormat("dd/MM/yyyy");
    int flag=1;
    /**
     * Creates new form FrmCadastraVeiculo
     */
    public FrmCadastraVeiculo() {
       initComponents();
     //  preencherTabela("SELECT *FROM veiculos where placa LIKE '%" + jTextFieldPesquisar.getText() + "%' ORDER BY placa ASC");
       preencherCombo();
       LimpaCampos();
       BloquearCampos();
       jTextFielddataCadastro.setText("");
       preencherTabela("SELECT *FROM veiculos ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldPlaca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxMarcas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldChassi = new javax.swing.JTextField();
        jTextFieldnumeroMotor = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldRenavam = new javax.swing.JTextField();
        jTextFieldCorInterna = new javax.swing.JTextField();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldCorExterna = new javax.swing.JTextField();
        jComboBoxCombustivel = new javax.swing.JComboBox<>();
        jComboBoxMotor = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxEspecie = new javax.swing.JComboBox<>();
        jTextFieldKilometragem = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxProprietario = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButtonFornecedor = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jComboBoxAnoModelo = new javax.swing.JComboBox<>();
        jComboBoxAnoFab = new javax.swing.JComboBox<>();
        jTextFielddataCadastro = new javax.swing.JTextField();
        jTextFieldID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonVisualizar = new javax.swing.JButton();
        jLabelCarregando = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 181, 181));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 32767));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 681));

        jButtonNovo.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNovo.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonNovo.setForeground(new java.awt.Color(0, 153, 153));
        jButtonNovo.setText("Novo (F6)");
        jButtonNovo.setToolTipText("Novo");
        jButtonNovo.setBorder(null);
        jButtonNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonSalvar.setForeground(new java.awt.Color(0, 153, 153));
        jButtonSalvar.setText("Salvar (F12)");
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.setBorder(null);
        jButtonSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEditar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonEditar.setForeground(new java.awt.Color(0, 153, 153));
        jButtonEditar.setText("Editar (F8)");
        jButtonEditar.setToolTipText("Editar");
        jButtonEditar.setBorder(null);
        jButtonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setBackground(new java.awt.Color(255, 255, 255));
        jButtonExcluir.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonExcluir.setForeground(new java.awt.Color(0, 153, 153));
        jButtonExcluir.setText("Excluir (Del)");
        jButtonExcluir.setToolTipText("Excluir");
        jButtonExcluir.setBorderPainted(false);
        jButtonExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonSair.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSair.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonSair.setForeground(new java.awt.Color(0, 153, 153));
        jButtonSair.setText("Sair (ESC)");
        jButtonSair.setToolTipText("Sair");
        jButtonSair.setBorderPainted(false);
        jButtonSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jTextFieldPesquisar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextFieldPesquisar.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldPesquisar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarActionPerformed(evt);
            }
        });
        jTextFieldPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyReleased(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));

        jTextFieldPlaca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldPlaca.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldPlaca.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Placa:");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ano Fabr.:");

        jComboBoxMarcas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxMarcas.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxMarcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fiat", "Chevrolet", "Volkswagen", "Ford", "Renault", "Toyota", "Citroen", "Nissan", "Chery", "Land Rover", "Jaguar", "Mitsubishi", "Peugeot", "Mercedes-Benz", "Caio", "Mini Cooper", "Honda" }));
        jComboBoxMarcas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Marca:");

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ano Mod.:");

        jTextFieldChassi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldChassi.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldChassi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldChassi.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        jTextFieldnumeroMotor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldnumeroMotor.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldnumeroMotor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldnumeroMotor.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Renavam:");

        jLabel25.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Chassi:");

        jLabel26.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Nº Motor:");

        jTextFieldRenavam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldRenavam.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldRenavam.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldRenavam.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        jTextFieldCorInterna.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldCorInterna.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldCorInterna.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldCorInterna.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        jTextFieldModelo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldModelo.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldModelo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldModelo.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        jTextFieldCorExterna.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldCorExterna.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldCorExterna.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldCorExterna.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        jComboBoxCombustivel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxCombustivel.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxCombustivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasolina", "Etanol", "Flex", "Hibrido", "Diesel" }));
        jComboBoxCombustivel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBoxCombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCombustivelActionPerformed(evt);
            }
        });

        jComboBoxMotor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxMotor.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxMotor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.0", "1.4", "1.6", "1.8", "2.0 S/Turbo", "2.0 Turbo", "3.0" }));
        jComboBoxMotor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBoxMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMotorActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Modelo:");

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Cor Externa:");

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cor Interna:");

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Combustivel:");

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Motor:");

        jComboBoxEspecie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxEspecie.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Passageiros", "Carga", "Misto", "Tração", "Competição", "Especial", "Coleção" }));
        jComboBoxEspecie.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBoxEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEspecieActionPerformed(evt);
            }
        });

        jTextFieldKilometragem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldKilometragem.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldKilometragem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldKilometragem.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Kilometragem:");

        jComboBoxProprietario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxProprietario.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxProprietario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBoxProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProprietarioActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Proprietario");

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Especie:");

        jButtonFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        jButtonFornecedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonFornecedor.setForeground(new java.awt.Color(0, 153, 153));
        jButtonFornecedor.setText("+");
        jButtonFornecedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonFornecedor.setBorderPainted(false);
        jButtonFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFornecedorActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Data do Cadastro:");

        jComboBoxAnoModelo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxAnoModelo.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxAnoModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", " " }));
        jComboBoxAnoModelo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBoxAnoModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAnoModeloActionPerformed(evt);
            }
        });

        jComboBoxAnoFab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxAnoFab.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxAnoFab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", " " }));
        jComboBoxAnoFab.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBoxAnoFab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAnoFabActionPerformed(evt);
            }
        });

        jTextFielddataCadastro.setEditable(false);
        jTextFielddataCadastro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFielddataCadastro.setForeground(new java.awt.Color(102, 102, 102));
        jTextFielddataCadastro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFielddataCadastro.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFielddataCadastro.setEnabled(false);

        jTextFieldID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldID.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jTextFieldCorExterna, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jTextFieldCorInterna, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jComboBoxCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jComboBoxAnoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(8, 8, 8))
                                    .addComponent(jComboBoxAnoFab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextFieldChassi))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldRenavam, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jTextFieldnumeroMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jComboBoxEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldKilometragem, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jComboBoxProprietario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jTextFielddataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldnumeroMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRenavam, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldChassi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jComboBoxAnoFab, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBoxAnoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldCorExterna, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldCorInterna, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jComboBoxMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel17)
                    .addComponent(jLabel9)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldKilometragem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFielddataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jButtonVisualizar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVisualizar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonVisualizar.setForeground(new java.awt.Color(0, 153, 153));
        jButtonVisualizar.setText("Visualizar Veiculos");
        jButtonVisualizar.setBorderPainted(false);
        jButtonVisualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarActionPerformed(evt);
            }
        });

        jLabelCarregando.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCarregando.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCarregando.setText("CARREGANDO RELATÓRIO...");

        jButtonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(0, 153, 153));
        jButtonCancelar.setText("Cancelar (F7)");
        jButtonCancelar.setToolTipText("Excluir");
        jButtonCancelar.setBorderPainted(false);
        jButtonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        tabela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelCarregando)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCarregando, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1263, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1279, 689));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        
        jTextFielddataCadastro.setText(data.format(hoje));
        HabilitarCampos();
        LimpaCampos();

        jTextFieldPesquisar.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(true);

        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        if (jTextFieldPlaca.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo PLACA esta sem preenchimento!");
            jTextFieldPlaca.requestFocus();

        }else if(jTextFieldChassi.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo CHASSI esta sem preenchimento!");
            jTextFieldChassi.requestFocus();

        }else if(jTextFieldRenavam.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo RENAVAM esta sem preenchimento!");
            jTextFieldRenavam.requestFocus();

        }else if(jTextFieldnumeroMotor.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informar o NUMERO DO MOTOR do veiculo!");
            jTextFieldnumeroMotor.requestFocus();

        }else if(jTextFieldModelo.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo MODELO esta sem preenchimento!");
            jTextFieldModelo.requestFocus();

        }else if(jTextFieldCorExterna.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo COR EXTERNA esta sem preenchimento!");
            jTextFieldCorExterna.requestFocus();

        }else if(jTextFieldCorInterna.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo COR INTERNA esta sem preenchimento!");
            jTextFieldCorInterna.requestFocus();

        }else if(jTextFieldKilometragem.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo COR EXTERNA esta sem preenchimento!");
            jTextFieldKilometragem.requestFocus();

        }else  if(flag==1) {
            
            
            mod.setPlaca(jTextFieldPlaca.getText());
            mod.setAnoModelo((String)jComboBoxAnoModelo.getSelectedItem());
            mod.setAnoFabricacao((String)jComboBoxAnoFab.getSelectedItem());
            mod.setChassi(jTextFieldChassi.getText());
            mod.setRenavam(jTextFieldRenavam.getText());
            mod.setNumeromotor(jTextFieldnumeroMotor.getText());
            mod.setMarca((String)jComboBoxMarcas.getSelectedItem());
            mod.setModelo(jTextFieldModelo.getText());
            mod.setCorExterna(jTextFieldCorExterna.getText());
            mod.setCorInterna(jTextFieldCorInterna.getText());
            mod.setCombustivel((String)jComboBoxCombustivel.getSelectedItem());
            mod.setMotor((String)jComboBoxMotor.getSelectedItem());
            mod.setEspecie((String)jComboBoxEspecie.getSelectedItem());
            mod.setKm(jTextFieldKilometragem.getText());
            mod.setProprietario((String)jComboBoxProprietario.getSelectedItem());
            mod.setDataCadastro(jTextFielddataCadastro.getText());
            
            
            control.InserirVeiculo(mod);
            
            preencherTabela("SELECT * FROM veiculos where placa LIKE '%" + jTextFieldPesquisar.getText() + "%' ORDER BY placa ASC");

            LimpaCampos();
            BloquearCampos();
            jTextFielddataCadastro.setText("");

            jTextFieldPesquisar.setEnabled(true);
            jButtonCancelar.setEnabled(false);
            jButtonExcluir.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonNovo.setEnabled(true);

        }else{

            
            
            
            mod.setAnoModelo((String)jComboBoxAnoModelo.getSelectedItem());
            mod.setAnoFabricacao((String)jComboBoxAnoFab.getSelectedItem());
            mod.setChassi(jTextFieldChassi.getText());
            mod.setRenavam(jTextFieldRenavam.getText());
            mod.setNumeromotor(jTextFieldnumeroMotor.getText());
            mod.setMarca((String)jComboBoxMarcas.getSelectedItem());
            mod.setModelo(jTextFieldModelo.getText());
            mod.setCorExterna(jTextFieldCorExterna.getText());
            mod.setCorInterna(jTextFieldCorInterna.getText());
            mod.setCombustivel((String)jComboBoxCombustivel.getSelectedItem());
            mod.setMotor((String)jComboBoxMotor.getSelectedItem());
            mod.setEspecie((String)jComboBoxEspecie.getSelectedItem());
            mod.setKm(jTextFieldKilometragem.getText());
            mod.setProprietario((String)jComboBoxProprietario.getSelectedItem());
            mod.setDataCadastro(jTextFielddataCadastro.getText());
            mod.setPlaca(jTextFieldPlaca.getText());
            mod.setIdVeiculo(Integer.parseInt(jTextFieldID.getText()));
            

            control.AlterarVeiculo(mod);
            preencherTabela("SELECT * FROM veiculos where placa LIKE '%" + jTextFieldPesquisar.getText() + "%' ORDER BY placa ASC");
            BloquearCampos();
            jTextFielddataCadastro.setText("");

            jTextFieldPesquisar.setEnabled(true);
            jButtonCancelar.setEnabled(false);
            jButtonExcluir.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonNovo.setEnabled(true);

            LimpaCampos();

        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 2;

        HabilitarCampos();
        jTextFieldPesquisar.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        String message = "Deseja Excluir Veiculo ?";
        String title = "Excluir Veiculo";

        int result = JOptionPane.showConfirmDialog(this, message, title, JOptionPane.YES_OPTION);

        if (result == JOptionPane.YES_OPTION) {

            mod.setPlaca(jTextFieldPlaca.getText());

            control.ExcluirVeiculo(mod);

            preencherTabela("SELECT * FROM veiculos where placa LIKE '%" + jTextFieldPesquisar.getText() + "%' ORDER BY placa ASC");

            BloquearCampos();
            LimpaCampos();

            jButtonSalvar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            jButtonCancelar.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jButtonExcluir.setEnabled(false);

        } else {

            JOptionPane.showMessageDialog(null, "Produto não Excluido");
        }

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jTextFieldPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarActionPerformed
       
    }//GEN-LAST:event_jTextFieldPesquisarActionPerformed

    private void jTextFieldPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyPressed
        //if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            

                preencherTabela("SELECT * FROM veiculos where placa LIKE '%" + jTextFieldPesquisar.getText() + "%' ORDER BY placa ASC");

       // }
    }//GEN-LAST:event_jTextFieldPesquisarKeyPressed

    private void jTextFieldPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyReleased
        preencherTabela("SELECT * FROM veiculos where placa LIKE '%" + jTextFieldPesquisar.getText() + "%' ORDER BY placa ASC");
    }//GEN-LAST:event_jTextFieldPesquisarKeyReleased

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        LimpaCampos();
        BloquearCampos();
        jTextFieldPesquisar.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jTextFielddataCadastro.setText("");

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked

       jButtonNovo.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonCancelar.setEnabled(true);

        BloquearCampos();
        String placa = "" + tabela.getValueAt(tabela.getSelectedRow(), 1);
        conecta.conexao();
        conecta.executaSQL("SELECT * FROM veiculos WHERE placa ='" + placa + "'");
        try {
            conecta.rs.first();
            jTextFieldID.setText(conecta.rs.getString("id_veiculos"));
            jTextFieldPlaca.setText(conecta.rs.getString("placa"));
            jComboBoxAnoModelo.setSelectedItem(conecta.rs.getString("ano_modelo"));
            jComboBoxAnoFab.setSelectedItem(conecta.rs.getString("ano_fabric"));
            jTextFieldChassi.setText(conecta.rs.getString("chassi"));
            jTextFieldRenavam.setText(conecta.rs.getString("renavam"));
            jTextFieldnumeroMotor.setText(conecta.rs.getString("numero_motor"));
            jComboBoxMarcas.setSelectedItem(conecta.rs.getString("marca"));
            jTextFieldModelo.setText(conecta.rs.getString("modelo"));
            jTextFieldCorExterna.setText(conecta.rs.getString("cor_externa"));
            jTextFieldCorInterna.setText(conecta.rs.getString("cor_interna"));
            jComboBoxCombustivel.setSelectedItem(conecta.rs.getString("combustivel"));
            jComboBoxMotor.setSelectedItem(conecta.rs.getString("motor"));
            jComboBoxEspecie.setSelectedItem(conecta.rs.getString("especie"));
            jTextFieldKilometragem.setText(conecta.rs.getString("km"));
            jComboBoxProprietario.setSelectedItem(conecta.rs.getString("proprietario"));
            jTextFielddataCadastro.setText(conecta.rs.getString("data_cadastro"));
             
            conecta.desconecta();
            //JOptionPane.showMessageDialog(null, placa);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Selecionar os Dados" + ex);
        } finally {

            conecta.desconecta();

        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void tabelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaKeyReleased
        jButtonNovo.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonCancelar.setEnabled(true);

        BloquearCampos();
        String placa = "" + tabela.getValueAt(tabela.getSelectedRow(), 1);
        conecta.conexao();
        conecta.executaSQL("SELECT * FROM veiculos WHERE placa ='" + placa + "'");
        try {
            conecta.rs.first();
            jTextFieldID.setText(conecta.rs.getString("id_veiculos"));
            jTextFieldPlaca.setText(conecta.rs.getString("placa"));
            jComboBoxAnoModelo.setSelectedItem(conecta.rs.getString("ano_modelo"));
            jComboBoxAnoFab.setSelectedItem(conecta.rs.getString("ano_fabric"));
            jTextFieldChassi.setText(conecta.rs.getString("chassi"));
            jTextFieldRenavam.setText(conecta.rs.getString("renavam"));
            jTextFieldnumeroMotor.setText(conecta.rs.getString("numero_motor"));
            jComboBoxMarcas.setSelectedItem(conecta.rs.getString("marca"));
            jTextFieldModelo.setText(conecta.rs.getString("modelo"));
            jTextFieldCorExterna.setText(conecta.rs.getString("cor_externa"));
            jTextFieldCorInterna.setText(conecta.rs.getString("cor_interna"));
            jComboBoxCombustivel.setSelectedItem(conecta.rs.getString("combustivel"));
            jComboBoxMotor.setSelectedItem(conecta.rs.getString("motor"));
            jComboBoxEspecie.setSelectedItem(conecta.rs.getString("especie"));
            jTextFieldKilometragem.setText(conecta.rs.getString("km"));
            jComboBoxProprietario.setSelectedItem(conecta.rs.getString("proprietario"));
            jTextFielddataCadastro.setText(conecta.rs.getString("data_cadastro"));
             
            conecta.desconecta();
            JOptionPane.showMessageDialog(null, placa);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, "Erro ao Selecionar os Dados" + ex);
        } finally {

            conecta.desconecta();

        }
    }//GEN-LAST:event_tabelaKeyReleased

    private void jComboBoxCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCombustivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCombustivelActionPerformed

    private void jComboBoxMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMotorActionPerformed

    private void jComboBoxEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEspecieActionPerformed

    private void jComboBoxProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProprietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProprietarioActionPerformed

    private void jButtonFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFornecedorActionPerformed
       FrmCadastrarClientes frm = new FrmCadastrarClientes();
        frm.setVisible(true);
        preencherCombo();
    }//GEN-LAST:event_jButtonFornecedorActionPerformed

    private void jButtonVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarActionPerformed
       new Thread(){
        
            
            public void run(){
                jLabelCarregando.setVisible(true);
                TarefasSegundoPlano t = new TarefasSegundoPlano();
                t.relatorioVeiculos();
                jLabelCarregando.setVisible(false);
                
            }
        
        }.start();
    }//GEN-LAST:event_jButtonVisualizarActionPerformed

    private void jComboBoxAnoModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAnoModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAnoModeloActionPerformed

    private void jComboBoxAnoFabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAnoFabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAnoFabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastraVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastraVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastraVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastraVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastraVeiculo().setVisible(true);
            }
        });
    }
    
    public void preencherCombo() {

        conecta.conexao();
        conecta.executaSQL("select * from clientes order by nome_cliente");
        try {
            conecta.rs.first();
            jComboBoxProprietario.removeAllItems();
            jComboBoxProprietario.addItem("");
            do {

                jComboBoxProprietario.addItem(conecta.rs.getString("nome_cliente"));

            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Selecionar os Dados" + ex);

        } finally {

            conecta.desconecta();

        }

        jComboBoxProprietario.setSelectedItem("NAO CADASTRADO");

    }
    
    public void preencherTabela(String SQL) {

        ArrayList dados = new ArrayList();

        String[] Colunas = new String[]{"ID","Placa","Ano Modelo","Ano Fabricação", "Chassi", "Renavam", "Nº Motor", "Marca", "Modelo",
        "Cor Externa","Cor Interna","Combustivel","Torque","Especie","KM","Proprietario","Data Cadastro"};
        conecta.conexao();
        conecta.executaSQL(SQL);
       
        try {

            conecta.rs.first();

            do {
                 
                dados.add(new Object[]{conecta.rs.getInt("id_veiculos"),conecta.rs.getString("placa"), conecta.rs.getString("ano_modelo"),conecta.rs.getString("ano_fabric"),
                    conecta.rs.getString("chassi"),conecta.rs.getString("renavam"),conecta.rs.getString("numero_motor"),conecta.rs.getString("marca"),
                    conecta.rs.getString("modelo"),conecta.rs.getString("cor_externa"),conecta.rs.getString("cor_interna"),
                    conecta.rs.getString("combustivel"),conecta.rs.getString("motor"), conecta.rs.getString("especie"),conecta.rs.getString("km"), 
                    conecta.rs.getString("proprietario"),conecta.rs.getString("data_cadastro")});
            } while (conecta.rs.next());
        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, "ERRO AO CONECTAR"+ e);
        }

        ModeloTabela modelo = new ModeloTabela(dados, Colunas);

        tabela.setModel(modelo);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(40); //ID
        tabela.getColumnModel().getColumn(0).setResizable(false);
        tabela.getColumnModel().getColumn(1).setPreferredWidth(80); //Placa
        tabela.getColumnModel().getColumn(1).setResizable(false);
        tabela.getColumnModel().getColumn(2).setPreferredWidth(100);// ANO MODELO
        tabela.getColumnModel().getColumn(2).setResizable(false);
        tabela.getColumnModel().getColumn(3).setPreferredWidth(100); //ANO FABRICAÇÃO
        tabela.getColumnModel().getColumn(3).setResizable(false);
        tabela.getColumnModel().getColumn(4).setPreferredWidth(150);// CHASSI
        tabela.getColumnModel().getColumn(4).setResizable(false);
        tabela.getColumnModel().getColumn(5).setPreferredWidth(120);// RENAVAM
        tabela.getColumnModel().getColumn(5).setResizable(false);
        tabela.getColumnModel().getColumn(6).setPreferredWidth(90); //NUMERO MOTOR
        tabela.getColumnModel().getColumn(6).setResizable(false);
        tabela.getColumnModel().getColumn(7).setPreferredWidth(100); //MARCA
        tabela.getColumnModel().getColumn(7).setResizable(false);
        tabela.getColumnModel().getColumn(8).setPreferredWidth(250); // MODELO
        tabela.getColumnModel().getColumn(8).setResizable(false);
        tabela.getColumnModel().getColumn(9).setPreferredWidth(100);// COR EXTERNA
        tabela.getColumnModel().getColumn(9).setResizable(false);
        tabela.getColumnModel().getColumn(10).setPreferredWidth(100); //COR INTERNA
        tabela.getColumnModel().getColumn(10).setResizable(false);
        tabela.getColumnModel().getColumn(11).setPreferredWidth(80);//COMBUSTIVEL
        tabela.getColumnModel().getColumn(11).setResizable(false);
        tabela.getColumnModel().getColumn(12).setPreferredWidth(65); //TORQUE
        tabela.getColumnModel().getColumn(12).setResizable(false);
        tabela.getColumnModel().getColumn(13).setPreferredWidth(120); //ESPECIE
        tabela.getColumnModel().getColumn(13).setResizable(false);
        tabela.getColumnModel().getColumn(14).setPreferredWidth(80);// KM
        tabela.getColumnModel().getColumn(14).setResizable(false);
        tabela.getColumnModel().getColumn(15).setPreferredWidth(250); // PROPRIETARIO
        tabela.getColumnModel().getColumn(15).setResizable(false);
        tabela.getColumnModel().getColumn(16).setPreferredWidth(90); // data cadastro
        tabela.getColumnModel().getColumn(16).setResizable(false);
       
        
        
        
        

        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.setAutoResizeMode(tabela.AUTO_RESIZE_OFF);
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tabela.setRowHeight(28);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFornecedor;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVisualizar;
    private javax.swing.JComboBox<String> jComboBoxAnoFab;
    private javax.swing.JComboBox<String> jComboBoxAnoModelo;
    private javax.swing.JComboBox<String> jComboBoxCombustivel;
    private javax.swing.JComboBox<String> jComboBoxEspecie;
    private javax.swing.JComboBox<String> jComboBoxMarcas;
    private javax.swing.JComboBox<String> jComboBoxMotor;
    private javax.swing.JComboBox<String> jComboBoxProprietario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCarregando;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldChassi;
    private javax.swing.JTextField jTextFieldCorExterna;
    private javax.swing.JTextField jTextFieldCorInterna;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldKilometragem;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldPlaca;
    private javax.swing.JTextField jTextFieldRenavam;
    private javax.swing.JTextField jTextFielddataCadastro;
    private javax.swing.JTextField jTextFieldnumeroMotor;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
private void novoProduto() {
        javax.swing.InputMap inputMap = this.getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F6, 0), "novo");
        this.getRootPane().setInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("novo", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            public void actionPerformed(ActionEvent arg0) {
                jButtonNovo.doClick();
            }
        });
    }

    private void salvaProduto() {
        javax.swing.InputMap inputMap = this.getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F12, 0), "salvar");
        this.getRootPane().setInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("salvar", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            public void actionPerformed(ActionEvent arg0) {
                jButtonSalvar.doClick();
            }
        });
    }

    private void EditaProduto() {
        javax.swing.InputMap inputMap = this.getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F8, 0), "edita");
        this.getRootPane().setInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("edita", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            public void actionPerformed(ActionEvent arg0) {
                jButtonEditar.doClick();
            }
        });
    }

    private void ExcluirProduto() {
        javax.swing.InputMap inputMap = this.getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_DELETE, 0), "exclui");
        this.getRootPane().setInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("exclui", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            public void actionPerformed(ActionEvent arg0) {
                jButtonExcluir.doClick();
            }
        });
    }

    private void Sair() {
        javax.swing.InputMap inputMap = this.getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "escape");
        this.getRootPane().setInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("escape", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            public void actionPerformed(ActionEvent arg0) {
                jButtonSair.doClick();
            }
        });
    }
      private void CancelarProduto() {
       javax.swing.InputMap inputMap = this.getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
                inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F7, 0),"cancela");
                this.getRootPane().setInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
                this.getRootPane().getActionMap().put("cancela", new AbstractAction(){
                private static final long serialVersionUID = 1L;
                public void actionPerformed(ActionEvent arg0) {            
                jButtonCancelar.doClick();
                
               
                }
            });
    }
    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    public void BloquearCampos(){
        
        jTextFieldPlaca.setEnabled(false);
        jComboBoxAnoModelo.setEnabled(false);
        jComboBoxAnoFab.setEnabled(false);
        jTextFieldChassi.setEnabled(false);
        jTextFieldRenavam.setEnabled(false);
        jTextFieldnumeroMotor.setEnabled(false);
        jComboBoxMarcas.setEnabled(false);
        jTextFieldModelo.setEnabled(false);
        jTextFieldCorExterna.setEnabled(false);
        jTextFieldCorInterna.setEnabled(false);
        jComboBoxCombustivel.setEnabled(false);
        jComboBoxMotor.setEnabled(false);
        jComboBoxEspecie.setEnabled(false);
        jTextFieldKilometragem.setEnabled(false);
        jComboBoxProprietario.setEnabled(false);
        jButtonFornecedor.setEnabled(false);
        jTextFieldID.setEnabled(false);
       
        
        
    }
    public void HabilitarCampos(){
        jTextFieldPlaca.setEnabled(true);
        jComboBoxAnoModelo.setEnabled(true);
        jComboBoxAnoFab.setEnabled(true);
        jTextFieldChassi.setEnabled(true);
        jTextFieldRenavam.setEnabled(true);
        jTextFieldnumeroMotor.setEnabled(true);
        jComboBoxMarcas.setEnabled(true);
        jTextFieldModelo.setEnabled(true);
        jTextFieldCorExterna.setEnabled(true);
        jTextFieldCorInterna.setEnabled(true);
        jComboBoxCombustivel.setEnabled(true);
        jComboBoxMotor.setEnabled(true);
        jComboBoxEspecie.setEnabled(true);
        jTextFieldKilometragem.setEnabled(true);
        jComboBoxProprietario.setEnabled(true);
        jButtonFornecedor.setEnabled(true);
       
        
    }
    
    public void LimpaCampos(){
         jTextFieldPlaca.setText("");
        jComboBoxAnoModelo.setSelectedIndex(-1);
        jComboBoxAnoFab.setSelectedIndex(-1);
        jTextFieldChassi.setText("");
        jTextFieldRenavam.setText("");
        jTextFieldnumeroMotor.setText("");
        jComboBoxMarcas.setSelectedIndex(-1);
        jTextFieldModelo.setText("");
        jTextFieldCorExterna.setText("");
        jTextFieldCorInterna.setText("");
        jComboBoxCombustivel.setSelectedIndex(-1);
        jComboBoxMotor.setSelectedIndex(-1);
        jComboBoxEspecie.setSelectedIndex(-1);
        jTextFieldKilometragem.setText("");
        jComboBoxProprietario.setSelectedIndex(-1);
        jTextFieldID.setText("");
        
       
    }
}

