/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConectaBanco;
import controle.ControleProdutos;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ModeloProduto;
import modelo.ModeloTabela;
import modelo.NimbusClasse;
import java.text.NumberFormat;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.AbstractAction;
import javax.swing.KeyStroke;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import util.TarefasSegundoPlano;


public class FrmEditarProduto extends javax.swing.JFrame {
 
    ConectaBanco conecta = new ConectaBanco();
    ConectaBanco conectapesquisa = new ConectaBanco();
    ConectaBanco conectacategoria = new ConectaBanco();
    ModeloProduto mod = new ModeloProduto();
    ModeloProduto model = new ModeloProduto();
    ControleProdutos control = new ControleProdutos();
    DecimalFormat df = new DecimalFormat("0.00");
    NimbusClasse n = new NimbusClasse();
    NumberFormat calculo;
    int index;
    float pv,p,precoCompra,lucroEsperado,precoVenda;
    
    public FrmEditarProduto(int index) {
         initComponents();         
         setIcon();
         preencherCombo();         
         jComboBoxCategorias.removeAllItems(); 
         preencherComboCategorias();
         
         chamaProduto(index);
         EditaProduto();
        
         Sair();
//         calculo = NumberFormat.getInstance();
//         calculo.setMinimumFractionDigits(2);
        
    }

    private FrmEditarProduto() {
         initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonEditar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPrecoCompra = new javax.swing.JTextField();
        jTextFieldPrecoVenda = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxFornecedor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldQuantidadeMinima = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldLucro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldLucroEsperado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldBarras = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxCategorias = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();

        jLabel8.setText("Lucro Esperado %");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");
        setBackground(new java.awt.Color(0, 204, 204));

        jPanel1.setBackground(new java.awt.Color(0, 181, 181));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 32767));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 681));

        jButtonEditar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEditar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonEditar.setForeground(new java.awt.Color(0, 153, 153));
        jButtonEditar.setText("Salvar alterações (F8)");
        jButtonEditar.setToolTipText("Editar");
        jButtonEditar.setBorder(null);
        jButtonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonSair.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSair.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonSair.setForeground(new java.awt.Color(0, 153, 153));
        jButtonSair.setText("Sair (ESC)");
        jButtonSair.setToolTipText("Sair");
        jButtonSair.setBorderPainted(false);
        jButtonSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Preço de compra: ");

        jTextFieldPrecoCompra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldPrecoCompra.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldPrecoCompra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldPrecoCompra.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldPrecoCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPrecoCompraFocusLost(evt);
            }
        });
        jTextFieldPrecoCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldPrecoCompraMouseClicked(evt);
            }
        });

        jTextFieldPrecoVenda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldPrecoVenda.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldPrecoVenda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldPrecoVenda.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldPrecoVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPrecoVendaFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Preço de venda: ");

        jComboBoxFornecedor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBoxFornecedor.setForeground(new java.awt.Color(51, 51, 51));
        jComboBoxFornecedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fornecedor:");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("+");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldQuantidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldQuantidade.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldQuantidade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldQuantidade.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Estoque:");

        jTextFieldQuantidadeMinima.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldQuantidadeMinima.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldQuantidadeMinima.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldQuantidadeMinima.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldQuantidadeMinima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldQuantidadeMinimaKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Estoque Minimo:");

        jTextFieldLucro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldLucro.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldLucro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldLucro.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldLucro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldLucroFocusLost(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Lucro de venda: ");

        jTextFieldLucroEsperado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldLucroEsperado.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldLucroEsperado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldLucroEsperado.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldLucroEsperado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldLucroEsperadoFocusLost(evt);
            }
        });
        jTextFieldLucroEsperado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLucroEsperadoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Margem bruta %");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldLucroEsperado, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBoxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldQuantidadeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldLucroEsperado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel7))
                            .addGap(43, 43, 43)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jTextFieldPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldQuantidadeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextFieldPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(43, 43, 43)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBoxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(71, 71, 71)))))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));

        jTextFieldCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldCodigo.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldCodigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldCodigo.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldCodigo.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Código:");

        jTextFieldBarras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldBarras.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldBarras.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Código de barras:");

        jTextFieldProduto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldProduto.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldProduto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldProduto.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome do produto:");

        jComboBoxCategorias.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBoxCategorias.setForeground(new java.awt.Color(51, 51, 51));
        jComboBoxCategorias.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Categoria:");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 153));
        jButton2.setText("+");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jComboBoxCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jButtonExcluir.setBackground(new java.awt.Color(255, 255, 255));
        jButtonExcluir.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonExcluir.setForeground(new java.awt.Color(0, 153, 153));
        jButtonExcluir.setText("Excluir produto (Del)");
        jButtonExcluir.setToolTipText("Excluir");
        jButtonExcluir.setBorderPainted(false);
        jButtonExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButtonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1163, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed
    public void Cadastrar(){
        
        conecta.conexao();
        String name = jTextFieldProduto.getText();
        conecta.executaSQL("select nome_produto from produto where nome_produto='"+name+"'");
        try {
            
            if(conecta.rs.next()){
            
             JOptionPane.showMessageDialog(null,"O Produto "+name +" já foi Cadastrado");
            
            }else{
            
            mod.setFornecedorProduto((String)jComboBoxFornecedor.getSelectedItem());
            mod.setCodigobarras(jTextFieldBarras.getText());
            mod.setNomeProduto(jTextFieldProduto.getText());
            mod.setPrecoCompra(precoCompra);
            mod.setLucroesperado(Float.parseFloat(jTextFieldLucroEsperado.getText().replace(",", ".")));
            mod.setPrecoVenda(pv);
            mod.setQtdProduto(Integer.parseInt(jTextFieldQuantidade.getText()));
            mod.setQuantidadeM(Integer.parseInt(jTextFieldQuantidadeMinima.getText()));
            mod.setCategoria((String)jComboBoxCategorias.getSelectedItem());
        control.InserirProduto(mod);
        
        limpaCampos();
       
            }  
        } catch (SQLException ex) {
            Logger.getLogger(FrmEditarProduto.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            
            conecta.desconecta();
        }
        
    }
    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        mod.setIdProduto(Integer.parseInt(jTextFieldCodigo.getText()));
        mod.setCodigobarras(jTextFieldBarras.getText());
        mod.setFornecedorProduto((String)jComboBoxFornecedor.getSelectedItem());
        mod.setNomeProduto(jTextFieldProduto.getText());
        mod.setPrecoCompra(Float.parseFloat(jTextFieldPrecoCompra.getText().replace(",",".")));
        mod.setLucroVenda(Float.parseFloat(jTextFieldLucro.getText().replace(",", ".")));
        mod.setLucroesperado(Float.parseFloat(jTextFieldLucroEsperado.getText().replace(",", ".")));
        mod.setPrecoVenda(Float.parseFloat(jTextFieldPrecoVenda.getText().replace(",",".")));
        mod.setQtdProduto(Integer.parseInt(jTextFieldQuantidade.getText()));
        mod.setQuantidadeM(Integer.parseInt(jTextFieldQuantidadeMinima.getText()));
        control.AlterarProduto(mod);
        FrmProdutos p = new FrmProdutos();
        p.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButtonEditarActionPerformed
    public void chamaProduto(int index){
       
           
//        
//        
//        jTextFieldPrecoCompra.setText(String.valueOf(pCompra).replace(".", ","));
//        jTextFieldLucroEsperado.setText(String.valueOf(pLucro).replace(".", ","));
//        jTextFieldPrecoVenda.setText(String.valueOf(pVenda).replace(".", ","));
        conecta.conexao();
        conectapesquisa.conexao();
        conectacategoria.conexao();
        conecta.executaSQL("SELECT * FROM produto WHERE id_produto ="+index);
        try {
            conecta.rs.first();
            jTextFieldCodigo.setText(String.valueOf(conecta.rs.getInt("id_produto")));
            jTextFieldBarras.setText(conecta.rs.getString("codigobarras"));
            jTextFieldProduto.setText(conecta.rs.getString("nome_produto"));           
            jTextFieldPrecoCompra.setText(String.valueOf(df.format(conecta.rs.getFloat("preco_compra")).replace(".",",")));
            jTextFieldLucro.setText(String.valueOf(df.format(conecta.rs.getFloat("lucrovenda")).replace(".",",")));
            jTextFieldLucroEsperado.setText(String.valueOf(df.format(conecta.rs.getFloat("lucro_esperado")).replace(".",",")));
            jTextFieldPrecoVenda.setText(String.valueOf(df.format(conecta.rs.getFloat("preco_venda")).replace(".",",")));
            
            jTextFieldQuantidade.setText(String.valueOf(conecta.rs.getInt("quantidade")));
            jTextFieldQuantidadeMinima.setText(String.valueOf(conecta.rs.getInt("quantidade_minima")));
            
            conectapesquisa.executaSQL("SELECT * FROM fornecedor WHERE id_fornecedor ="+ conecta.rs.getInt("id_fornecedor"));
            conectapesquisa.rs.first();            
            jComboBoxFornecedor.setSelectedItem(conectapesquisa.rs.getString("nome_fornecedor"));
            
            
            conectacategoria.executaSQL("SELECT * FROM categorias WHERE id_categoria ="+ conecta.rs.getInt("id_categoria"));
            conectacategoria.rs.first();            
            jComboBoxCategorias.setSelectedItem(conectacategoria.rs.getString("nome_categoria"));
            
            conectacategoria.desconecta();
            conectapesquisa.desconecta();
            conecta.desconecta();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(FrmEditarProduto.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            
            conecta.desconecta();
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrmFornecedores frm = new FrmFornecedores();
        frm.setVisible(true);        
        preencherCombo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FrmCategorias cat = new FrmCategorias();
        cat.setVisible(true);      
        jComboBoxCategorias.removeAllItems();
        preencherComboCategorias();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldPrecoCompraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPrecoCompraFocusLost
       String pegaValor = jTextFieldPrecoCompra.getText();       
       String novoValor = pegaValor.replace(" ", "").replace(".", "").replace(",", ".");
       precoCompra = Float.parseFloat(novoValor);       
       DecimalFormat df = new DecimalFormat("0.00");
       String valorFormatado = df.format(precoCompra);
       jTextFieldPrecoCompra.setText(valorFormatado);
       
        
        
    }//GEN-LAST:event_jTextFieldPrecoCompraFocusLost

    private void jTextFieldPrecoCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPrecoCompraMouseClicked
        
        jTextFieldPrecoCompra.selectAll();
    }//GEN-LAST:event_jTextFieldPrecoCompraMouseClicked

    private void jTextFieldPrecoVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPrecoVendaFocusLost
        float precoCompra = Float.parseFloat(jTextFieldPrecoCompra.getText().replace(",", "."));
        
        float precoVenda = Float.parseFloat(jTextFieldPrecoVenda.getText().replace(",", "."));
        float lucro = precoVenda - precoCompra;
        float p = (lucro / precoVenda) * 100;
        
         
         String pcf = df.format(p);
         jTextFieldPrecoCompra.setText(String.valueOf(df.format(precoCompra)));
         jTextFieldPrecoVenda.setText(String.valueOf(df.format(precoVenda)));      
         jTextFieldLucroEsperado.setText(String.valueOf(pcf));
         jTextFieldLucro.setText(String.valueOf(df.format(lucro)));
         
        
    }//GEN-LAST:event_jTextFieldPrecoVendaFocusLost

    private void jTextFieldQuantidadeMinimaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeMinimaKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           
           Cadastrar();
           
       }
    }//GEN-LAST:event_jTextFieldQuantidadeMinimaKeyPressed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        String message = "Deseja Excluir Produto ?";
        String title = "Excluir Produto";

        int result = JOptionPane.showConfirmDialog(this, message, title, JOptionPane.YES_OPTION);

        if(result == JOptionPane.YES_OPTION){

            mod.setIdProduto(Integer.parseInt(jTextFieldCodigo.getText()));
            control.ExcluirProduto(mod);
            FrmProdutos p = new FrmProdutos();
            p.setVisible(true);
            dispose();
        }else{

            JOptionPane.showMessageDialog(null,"Produto não Excluido");
        }

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTextFieldLucroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLucroFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLucroFocusLost

    private void jTextFieldLucroEsperadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLucroEsperadoFocusLost
        String recebePCompra = jTextFieldPrecoCompra.getText().replace(",",".");

        float precoCompra = Float.parseFloat(recebePCompra);

        float lucroEsperado = Float.parseFloat(jTextFieldLucroEsperado.getText().replace(",", "."));

        pv = (precoCompra * lucroEsperado) / 100 + precoCompra;

        jTextFieldPrecoCompra.setText(String.valueOf(df.format(precoCompra)));
        //jTextFieldPrecoVenda.setText(String.valueOf(df.format(pv)));

    }//GEN-LAST:event_jTextFieldLucroEsperadoFocusLost

    private void jTextFieldLucroEsperadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLucroEsperadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLucroEsperadoActionPerformed
    
    
    public void preencherCombo(){
        
       conecta.conexao();
       conecta.executaSQL("select * from fornecedor order by nome_fornecedor");
        try {
            conecta.rs.first();
            jComboBoxFornecedor.removeAllItems();
            do {                
                
                jComboBoxFornecedor.addItem(conecta.rs.getString("nome_fornecedor"));
                
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao Selecionar os Dados"+ ex);
            conecta.desconecta();
        }finally{
            
            conecta.desconecta();
        }
        
    }
    
    public void preencherComboCategorias(){
        
       conecta.conexao();
       conecta.executaSQL("select * from categorias order by nome_categoria");
        try {
            conecta.rs.first();
            jComboBoxCategorias.removeAllItems();
            do {                
                
                jComboBoxCategorias.addItem(conecta.rs.getString("nome_categoria"));
                
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao Selecionar os Dados"+ ex);
            conecta.desconecta();
        }finally{
            
            conecta.desconecta();
        }
        
    }
    public void limpaCampos(){
        jTextFieldBarras.setText("");
        jTextFieldCodigo.setText("");
        jTextFieldPrecoCompra.setText("");
        jTextFieldLucroEsperado.setText("");
        jTextFieldPrecoVenda.setText("");
        jTextFieldProduto.setText("");
        jTextFieldQuantidadeMinima.setText("");
        jTextFieldQuantidade.setText("");
        
    }
    
   
    
    public void desabilitarCampos(){
        
        jTextFieldBarras.setEnabled(false);
        jTextFieldLucroEsperado.setEnabled(false);
        jTextFieldPrecoCompra.setEnabled(false);
        jTextFieldPrecoVenda.setEnabled(false);
        jTextFieldProduto.setEnabled(false);
        jTextFieldQuantidade.setEnabled(false);
        jTextFieldQuantidadeMinima.setEnabled(false);
       
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEditarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox<String> jComboBoxCategorias;
    private javax.swing.JComboBox<String> jComboBoxFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldBarras;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldLucro;
    private javax.swing.JTextField jTextFieldLucroEsperado;
    private javax.swing.JTextField jTextFieldPrecoCompra;
    private javax.swing.JTextField jTextFieldPrecoVenda;
    private javax.swing.JTextField jTextFieldProduto;
    private javax.swing.JTextField jTextFieldQuantidade;
    private javax.swing.JTextField jTextFieldQuantidadeMinima;
    // End of variables declaration//GEN-END:variables

    
    
    private void EditaProduto() {
       javax.swing.InputMap inputMap = this.getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
                inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F8, 0),"edita");
                this.getRootPane().setInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
                this.getRootPane().getActionMap().put("edita", new AbstractAction(){
                private static final long serialVersionUID = 1L;
                public void actionPerformed(ActionEvent arg0) {            
                jButtonEditar.doClick();
                }
            });   
    }
    
   
    
    private void Sair() {
       javax.swing.InputMap inputMap = this.getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
                inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),"escape");
                this.getRootPane().setInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
                this.getRootPane().getActionMap().put("escape", new AbstractAction(){
                private static final long serialVersionUID = 1L;
                public void actionPerformed(ActionEvent arg0) {            
                jButtonSair.doClick();
                }
            });   
    }

    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
