/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConectaBanco;
import controle.ControleOs;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.ResourceBundle.Control;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ModeloOs;
import modelo.ModeloTabela;

/**
 *
 * @author TI RAMASA
 */
public class FrmMecanico extends javax.swing.JFrame {

    ConectaBanco conecta = new ConectaBanco();
    ModeloOs mod = new ModeloOs();
    ControleOs conn = new ControleOs();
    /**
     * Creates new form FrmMecanico
     */
    public FrmMecanico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaServico = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaProduto = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelaReclamacoes = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();
        jComboBoxSituacao = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNOS = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonLocalizar = new javax.swing.JButton();
        jComboBoxVeiculo = new javax.swing.JComboBox<>();
        jComboBoxCliente = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultar OS");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 181, 181));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        TabelaServico.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TabelaServico.setForeground(new java.awt.Color(102, 102, 102));
        TabelaServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TabelaServico);

        TabelaProduto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TabelaProduto.setForeground(new java.awt.Color(102, 102, 102));
        TabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TabelaProduto);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Produtos");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Serviços");

        TabelaReclamacoes.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TabelaReclamacoes.setForeground(new java.awt.Color(102, 102, 102));
        TabelaReclamacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(TabelaReclamacoes);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Reclamações");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(259, 259, 259)
                                .addComponent(jLabel7))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(223, 223, 223)
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jButtonAtualizar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAtualizar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonAtualizar.setForeground(new java.awt.Color(0, 102, 102));
        jButtonAtualizar.setText("Atualizar OS");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jButtonImprimir.setBackground(new java.awt.Color(255, 255, 255));
        jButtonImprimir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonImprimir.setForeground(new java.awt.Color(0, 102, 102));
        jButtonImprimir.setText("Imprimir OS");

        jComboBoxSituacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxSituacao.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aguardando aprovação da Seguradora", "Aguardando aprovação do Cliente", "Aguardando Entrega", "Aguardando Peça", "Aguardando Serviço", "Em Serviço", "Executando Serviço", "Serviço Parasilado", "teste" }));
        jComboBoxSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSituacaoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Situação:");

        jTextFieldNOS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldNOS.setForeground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nº OS");

        jButtonLocalizar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonLocalizar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonLocalizar.setForeground(new java.awt.Color(0, 102, 102));
        jButtonLocalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LUPA.png"))); // NOI18N
        jButtonLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocalizarActionPerformed(evt);
            }
        });

        jComboBoxVeiculo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jComboBoxVeiculo.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxVeiculo.setEnabled(false);

        jComboBoxCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxCliente.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxCliente.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Veiculo");

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Cliente");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextFieldNOS, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNOS, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(1, 1, 1)))
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        
        mod.setSituacao((String)jComboBoxSituacao.getSelectedItem());
        mod.setOs(Integer.parseInt(jTextFieldNOS.getText()));
        
        conn.AtualizaSituacaoOficina(mod);
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocalizarActionPerformed

        conecta.conexao();
        conecta.executaSQL("SELECT * FROM tab_os WHERE os like '%" + jTextFieldNOS.getText()+ "%'");

        try {
//                jComboBoxCliente.removeAllItems();
//                jComboBoxVeiculo.removeAllItems();
//                jComboBoxSituacao.removeAllItems();
                

            do{
                conecta.rs.first();
                
                jComboBoxCliente.addItem(conecta.rs.getString("cliente_os"));
                jComboBoxVeiculo.addItem(conecta.rs.getString("modelo_os"));
                jComboBoxSituacao.setSelectedItem(conecta.rs.getString("situacao_os"));
                

            } while (conecta.rs.next());
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, "Erro ao Selecionar os Dados" + ex);
        } finally {

            conecta.desconecta();
        }
        preencherTabelaProdutos("SELECT * FROM tab_os_produtos WHERE os LIKE '%" + jTextFieldNOS.getText()+ "%'");
        preencherTabelaServiços("SELECT * FROM tab_os_servico WHERE os LIKE '%" + jTextFieldNOS.getText() + "%' ORDER BY os ASC");
        preencherTabelaReclamação("SELECT * FROM tab_os WHERE os LIKE '%" + jTextFieldNOS.getText() + "%' ORDER BY os ASC");
        
    }//GEN-LAST:event_jButtonLocalizarActionPerformed

    private void jComboBoxSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSituacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSituacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMecanico().setVisible(true);
            }
        });
    }
    public void preencherTabelaProdutos(String SQL) {

        ArrayList dados = new ArrayList();

        String[] Colunas = new String[]{"Descrição","Quantidade"};
        conecta.conexao();
        conecta.executaSQL(SQL);

        try {

            conecta.rs.first();

            do {
                
                dados.add(new Object[]{conecta.rs.getString("nome_produto"),conecta.rs.getString("quantidade")}); 
            } while (conecta.rs.next());
            } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Produto não cadastrado!"+ e);
        } finally {

            conecta.desconecta();
        }

        ModeloTabela modelo = new ModeloTabela(dados, Colunas);

        TabelaProduto.setModel(modelo);
        TabelaProduto.getColumnModel().getColumn(0).setPreferredWidth(205); // ID
        TabelaProduto.getColumnModel().getColumn(0).setResizable(false);
        TabelaProduto.getColumnModel().getColumn(1).setPreferredWidth(80); // Nome Cliente
        TabelaProduto.getColumnModel().getColumn(1).setResizable(false);
        
       
        
        TabelaProduto.getTableHeader().setReorderingAllowed(false);
        TabelaProduto.setAutoResizeMode(TabelaProduto.AUTO_RESIZE_OFF);
        TabelaProduto.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TabelaProduto.setRowHeight(28);

    }
    public void preencherTabelaServiços(String SQL) {

        ArrayList dados = new ArrayList();

        String[] Colunas = new String[]{"Serviço","Tempo"};
        conecta.conexao();
        conecta.executaSQL(SQL);

        try {

            conecta.rs.first();

            do {
                
                dados.add(new Object[]{ conecta.rs.getString("descricao"),conecta.rs.getString("tempo")}); 
            } while (conecta.rs.next());
            } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Serviço não cadastrado!");
        } finally {

            conecta.desconecta();
        }

        ModeloTabela modelo = new ModeloTabela(dados, Colunas);

        TabelaServico.setModel(modelo);
        TabelaServico.getColumnModel().getColumn(0).setPreferredWidth(255); // ID
        TabelaServico.getColumnModel().getColumn(0).setResizable(false);
        TabelaServico.getColumnModel().getColumn(1).setPreferredWidth(50); // Nome Cliente
        TabelaServico.getColumnModel().getColumn(1).setResizable(false);
        
       
        
        TabelaServico.getTableHeader().setReorderingAllowed(false);
        TabelaServico.setAutoResizeMode(TabelaServico.AUTO_RESIZE_OFF);
        TabelaServico.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TabelaServico.setRowHeight(28);

    }
    public void preencherTabelaReclamação(String SQL) {

        ArrayList dados = new ArrayList();

        String[] Colunas = new String[]{"OS","Reclamação"};
        conecta.conexao();
        conecta.executaSQL(SQL);

        try {

            conecta.rs.first();

            do {
                
                dados.add(new Object[]{conecta.rs.getInt("os"),conecta.rs.getString("reclamacao1")}); 
            } while (conecta.rs.next());
            } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Reclamação não cadastrada!");
        } finally {

            conecta.desconecta();
        }

        ModeloTabela modelo = new ModeloTabela(dados, Colunas);

        TabelaReclamacoes.setModel(modelo);
        TabelaReclamacoes.getColumnModel().getColumn(0).setPreferredWidth(50); 
        TabelaReclamacoes.getColumnModel().getColumn(0).setResizable(false);
        TabelaReclamacoes.getColumnModel().getColumn(1).setPreferredWidth(800); 
        TabelaReclamacoes.getColumnModel().getColumn(1).setResizable(false);
        
        TabelaReclamacoes.getTableHeader().setReorderingAllowed(false);
        TabelaReclamacoes.setAutoResizeMode(TabelaServico.AUTO_RESIZE_OFF);
        TabelaReclamacoes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TabelaReclamacoes.setRowHeight(28);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaProduto;
    private javax.swing.JTable TabelaReclamacoes;
    private javax.swing.JTable TabelaServico;
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonLocalizar;
    private javax.swing.JComboBox<String> jComboBoxCliente;
    private javax.swing.JComboBox<String> jComboBoxSituacao;
    private javax.swing.JComboBox<String> jComboBoxVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextFieldNOS;
    // End of variables declaration//GEN-END:variables
}
